### ISSUE TITLE
Font Family

### ISSUE THREAD

**Issue by Harshitha-syn** [joinspontaneous/react-native-loading-spinner-overlay#103]
Below is the code snippet in which am trying to provide font-family to the spinner text. It is only taking the color and size but not the font family. Kindly revert if there is any solution for this.

<Spinner visible={spin} textContent={'Loading...'} textStyle={styles.spinnerTextStyle}/>
Provided styling:
spinnerTextStyle: {color: '#FFF', fontFamily: 'Avenir-Heavy', fontSize:17}

**Comment by ahmedmohamedxyz** [comment]
could you give screenshot of the text after you apply the new font.

**Comment by Harshitha-syn** [comment]
![Loader](https://user-images.githubusercontent.com/53002216/93200372-45a29400-f76d-11ea-93d0-ec42f6217bfb.png)
I tried giving this styling fontFamily: 'Avenir-Heavy'. But it is still the same even after giving the font family.

**Comment by Harshitha-syn** [comment]
> could you give screenshot of the text after you apply the new font.
I tried giving this styling fontFamily: 'Avenir-Heavy'. But as shown in the attached screenshot, it is still the same even after giving the font family.
![Loader](https://user-images.githubusercontent.com/53002216/93200883-06287780-f76e-11ea-81c6-002ca14fd131.png)

**Comment by amirhs712** [comment]
@Harshitha-syn 

React Native has trouble with `fontWeight: bold` which is why your `fontFamily` is not working correctly.
A workaround can be to set `fontWeight` in your `spinnerTextStyle` to anything other than `bold` (which overrides the default bold fontWeight set by the package).

In the end, I don't think this is an issue with the package itself.
