### ISSUE TITLE
request for collaborator: add react-native-mock tests

### ISSUE THREAD

**Issue by niftylettuce** [joinspontaneous/react-native-loading-spinner-overlay#24]
looking for a collaborator/contributor to add this

**Comment by Chris-Petty** [comment]
Just want to throw out there that Jest recently put out experimental RN support, so that might be something to look into alternatively (probably better long term as it matures). I haven't had a chance to use it yet and don't have time at the moment to help here unfortunately.

http://facebook.github.io/jest/blog/2016/07/27/jest-14.html#experimental-react-native-support

**Comment by vomchik** [comment]
@niftylettuce  I agree with @Chris-Petty. Jest it's more a preferable tool for testing. I will try to write some test in the near future.

**Comment by niftylettuce** [comment]
that'd be awesome and greatly appreciated @vomchik - more help the better

**Comment by vomchik** [comment]
I started to write test. You can assign this issue to me.

**Comment by niftylettuce** [comment]
@vomchik Hey, I invited you as a collaborator - once you accept, I can assign this issue to you, thanks again.

**Comment by vomchik** [comment]
Cool, when i finish i will create PR.
